# Generated by Django 2.2.4 on 2021-12-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank')], max_length=120, null=True),
        ),
    ]
