# Generated by Django 2.2.4 on 2021-12-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_type',
        ),
    ]
