# Generated by Django 2.2.4 on 2021-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing')], max_length=120),
        ),
    ]
