# Generated by Django 2.2.4 on 2021-12-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank')], max_length=120, null=True),
        ),
    ]
