# Generated by Django 2.2.4 on 2021-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='registries',
            field=models.ManyToManyField(blank=True, to='pipes_shop.Registry'),
        ),
        migrations.AddField(
            model_name='manual',
            name='notes',
            field=models.ManyToManyField(blank=True, to='pipes_shop.Note'),
        ),
    ]
