# Generated by Django 2.2.4 on 2021-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0002_auto_20210919_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
