# Generated by Django 2.2.4 on 2021-09-29 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0003_auto_20210919_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
