# Generated by Django 2.2.4 on 2021-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0005_pipe_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
