# Generated by Django 2.2.4 on 2021-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0007_pipe_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
