# Generated by Django 2.2.4 on 2021-12-04 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0008_auto_20211121_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
