# Generated by Django 2.2.4 on 2021-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipes_shop', '0009_auto_20211204_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='offline_buyer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
